//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APITokenTbl
    {
        public int APITokenID { get; set; }
        public string APIName { get; set; }
        public string APIKey { get; set; }
        public string SenderID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTest { get; set; }
        public string IsChannel { get; set; }
        public string IsUnicord { get; set; }
        public string IsFlash { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Route { get; set; }
    }
}
