//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssignmentTbl()
        {
            this.StudentAssignmentTbls = new HashSet<StudentAssignmentTbl>();
        }
    
        public long AssignmentID { get; set; }
        public Nullable<long> SubjectID { get; set; }
        public string Topic { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DeadLineOn { get; set; }
        public Nullable<System.DateTime> PublishedOn { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual SubjectTbl SubjectTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAssignmentTbl> StudentAssignmentTbls { get; set; }
    }
}
