//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChapterTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChapterTbl()
        {
            this.StudyMeterialTbls = new HashSet<StudyMeterialTbl>();
            this.VideoTbls = new HashSet<VideoTbl>();
        }
    
        public long ChapterID { get; set; }
        public Nullable<long> SubjectID { get; set; }
        public string ChapterName { get; set; }
    
        public virtual SubjectTbl SubjectTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudyMeterialTbl> StudyMeterialTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoTbl> VideoTbls { get; set; }
    }
}
