//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamTbl()
        {
            this.ExamQuestionTbls = new HashSet<ExamQuestionTbl>();
            this.StudentExamTbls = new HashSet<StudentExamTbl>();
        }
    
        public long ExamID { get; set; }
        public Nullable<long> SubjectID { get; set; }
        public string ExamName { get; set; }
        public Nullable<System.DateTime> ConductDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamQuestionTbl> ExamQuestionTbls { get; set; }
        public virtual SubjectTbl SubjectTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentExamTbl> StudentExamTbls { get; set; }
    }
}
