//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningHub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTbl> AdminTbls { get; set; }
        public virtual DbSet<APITokenTbl> APITokenTbls { get; set; }
        public virtual DbSet<AssignmentTbl> AssignmentTbls { get; set; }
        public virtual DbSet<ChapterTbl> ChapterTbls { get; set; }
        public virtual DbSet<ClassTbl> ClassTbls { get; set; }
        public virtual DbSet<CollegeTbl> CollegeTbls { get; set; }
        public virtual DbSet<CredentialTbl> CredentialTbls { get; set; }
        public virtual DbSet<DepartmentTbl> DepartmentTbls { get; set; }
        public virtual DbSet<ExamQuestionTbl> ExamQuestionTbls { get; set; }
        public virtual DbSet<ExamTbl> ExamTbls { get; set; }
        public virtual DbSet<MessageTbl> MessageTbls { get; set; }
        public virtual DbSet<MesSendTbl> MesSendTbls { get; set; }
        public virtual DbSet<MsgTransTbl> MsgTransTbls { get; set; }
        public virtual DbSet<ParentTbl> ParentTbls { get; set; }
        public virtual DbSet<RoleTbl> RoleTbls { get; set; }
        public virtual DbSet<StaffAssignClassTbl> StaffAssignClassTbls { get; set; }
        public virtual DbSet<StaffAttendanceTbl> StaffAttendanceTbls { get; set; }
        public virtual DbSet<StaffTbl> StaffTbls { get; set; }
        public virtual DbSet<StudentAssignmentTbl> StudentAssignmentTbls { get; set; }
        public virtual DbSet<StudentClassAttend> StudentClassAttends { get; set; }
        public virtual DbSet<StudentExamResultTbl> StudentExamResultTbls { get; set; }
        public virtual DbSet<StudentExamTbl> StudentExamTbls { get; set; }
        public virtual DbSet<StudentsAttentanceTbl> StudentsAttentanceTbls { get; set; }
        public virtual DbSet<StudentTbl> StudentTbls { get; set; }
        public virtual DbSet<StudyMeterialTbl> StudyMeterialTbls { get; set; }
        public virtual DbSet<SubjectTbl> SubjectTbls { get; set; }
        public virtual DbSet<SuperAdminTbl> SuperAdminTbls { get; set; }
        public virtual DbSet<VideoTbl> VideoTbls { get; set; }
    }
}
