//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesSendTbl
    {
        public long MsgSendID { get; set; }
        public Nullable<long> MsgTransID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string MessageText { get; set; }
    
        public virtual ParentTbl ParentTbl { get; set; }
        public virtual MsgTransTbl MsgTransTbl { get; set; }
    }
}
