//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageTbl
    {
        public long MsgID { get; set; }
        public string MessageText { get; set; }
        public string FirstPara { get; set; }
        public string SecondPara { get; set; }
        public string ThirdPara { get; set; }
        public string FourthPara { get; set; }
        public string FifthPara { get; set; }
    }
}
