//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffTbl()
        {
            this.StaffAssignClassTbls = new HashSet<StaffAssignClassTbl>();
            this.StaffAttendanceTbls = new HashSet<StaffAttendanceTbl>();
        }
    
        public long StaffID { get; set; }
        public Nullable<long> CredID { get; set; }
        public string StaffName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SkypeUserName { get; set; }
        public Nullable<bool> IsHead { get; set; }
        public Nullable<int> DeptID { get; set; }
    
        public virtual CredentialTbl CredentialTbl { get; set; }
        public virtual DepartmentTbl DepartmentTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffAssignClassTbl> StaffAssignClassTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffAttendanceTbl> StaffAttendanceTbls { get; set; }
    }
}
