//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffAssignClassTbl
    {
        public long AllotedClassID { get; set; }
        public Nullable<long> StaffID { get; set; }
        public Nullable<int> ClassID { get; set; }
    
        public virtual ClassTbl ClassTbl { get; set; }
        public virtual StaffTbl StaffTbl { get; set; }
    }
}
