//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTbl()
        {
            this.StudentAssignmentTbls = new HashSet<StudentAssignmentTbl>();
            this.StudentClassAttends = new HashSet<StudentClassAttend>();
            this.StudentExamTbls = new HashSet<StudentExamTbl>();
            this.StudentsAttentanceTbls = new HashSet<StudentsAttentanceTbl>();
        }
    
        public long StudentID { get; set; }
        public Nullable<long> CredID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string StudentName { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ClassTbl ClassTbl { get; set; }
        public virtual CredentialTbl CredentialTbl { get; set; }
        public virtual ParentTbl ParentTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAssignmentTbl> StudentAssignmentTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClassAttend> StudentClassAttends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentExamTbl> StudentExamTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsAttentanceTbl> StudentsAttentanceTbls { get; set; }
    }
}
