//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExamTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentExamTbl()
        {
            this.StudentExamResultTbls = new HashSet<StudentExamResultTbl>();
        }
    
        public long StudentExamID { get; set; }
        public Nullable<long> StudentID { get; set; }
        public Nullable<long> ExamID { get; set; }
        public Nullable<int> TotalAttendQuestion { get; set; }
        public Nullable<int> TotalCurrectAnwer { get; set; }
        public Nullable<int> TotalWrongAnswer { get; set; }
    
        public virtual ExamTbl ExamTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentExamResultTbl> StudentExamResultTbls { get; set; }
        public virtual StudentTbl StudentTbl { get; set; }
    }
}
