//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAssignmentTbl
    {
        public long StudentAssignmentID { get; set; }
        public Nullable<long> StudentID { get; set; }
        public Nullable<long> AssignmentID { get; set; }
        public string MeterailPath { get; set; }
        public Nullable<int> AssignmentMark { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<bool> IsStaffApprove { get; set; }
        public Nullable<bool> IsHODApprove { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual AssignmentTbl AssignmentTbl { get; set; }
        public virtual StudentTbl StudentTbl { get; set; }
    }
}
