//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentClassAttend
    {
        public long StudentClassAttID { get; set; }
        public Nullable<long> StudentID { get; set; }
        public Nullable<long> SubjectID { get; set; }
        public Nullable<System.DateTime> PresentDate { get; set; }
        public Nullable<System.DateTime> OpenTime { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual StudentTbl StudentTbl { get; set; }
        public virtual SubjectTbl SubjectTbl { get; set; }
    }
}
