//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoTbl
    {
        public long VideoID { get; set; }
        public Nullable<long> ChapterID { get; set; }
        public string VideoLink { get; set; }
        public string VideoTitle { get; set; }
        public Nullable<System.DateTime> PublishedOn { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ChapterTbl ChapterTbl { get; set; }
    }
}
